print("starting line")
a=[11, 22, 33, 44, 55, 66]
try:
    a=10/5
    print(a[4])
    print(a)
except ZeroDivisionError:
    print("exception raise due to zero division error")
except IndexError:
    print("exception raise due to index out of range") 
except NameError:
    print("exception raised due to undefined variable" )
except:
    print("some exception raised")           
else:
    print("No exception raiseed,everything worked perfectly")
finally:
    print("This is a final block")
print("Outside try block") 
